### ISSUE TITLE
是否可以预编译一份适配OpenWrt 19.07.3？

### ISSUE THREAD

**Issue by shikkoku** [goldkeyber112/openwrt-8168#1]
目前提供的预编译文件不支持在X86_64上的OpenWrt 19.07.3安装，需要内核为4.14.180的。希望能在Releases提供一份适用于原版OpenWrt的。

**Comment by shenlijun** [comment]
作者不一定是中国人

[kmod-r8168_4.14.180+8.048.03-x86-1_x86_64.zip](https://github.com/goldkeyber112/openwrt-r8168/files/5179090/kmod-r8168_4.14.180%2B8.048.03-x86-1_x86_64.zip)

**Comment by shikkoku** [comment]
> 作者不一定是中国人
> 
> [kmod-r8168_4.14.180+8.048.03-x86-1_x86_64.zip](https://github.com/goldkeyber112/openwrt-r8168/files/5179090/kmod-r8168_4.14.180%2B8.048.03-x86-1_x86_64.zip)

但他一定会看中文
https://github.com/BROBIRD/openwrt-r8168/issues/3#issuecomment-643938975

感谢你的编译，辛苦了。
